x = ['zero',
     'jeden',
     'dwa',
     'trzy',
     'cztery',
     'piec',
     'szesc',
     'siedem',
     'osiem',
     'dziewiec',
     'dziesiec',
     'jedenascie',
     'dwanascie',
     'trzynascie',
     'czternascie',
     'pietnascie',
     'szesnascie',
     'siedemnascie',
     'osiemnascie',
     'dziewietnascie']

xx = ['dwadziescia',
      'trzydziesci',
      'czterdziesci',
      'piecdziesiat',
      'szescdziesiat',
      'siedemdziesiat',
      'osiemdziesiat',
      'dziewiecdziesiat']

xxx = ['sto',
       'dwiescie',
       'trzysta',
       'czterysta',
       'piecset',
       'szescset',
       'siedemset',
       'osiemset',
       'dziewiecset']

bignumbers = ['', 'tysiac', 'milion', 'miliard', 'trylion', 'tryliard']